language: node_js

node_js:
  - 8.16
  - 10

# Build only commits on master and release tags preventing double builds for PRs
# See https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master
    - /v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

cache: npm

env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

# TODO: move in script
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint:test
  - npm run test:report
  - npm run test:coveralls

after_script:
  - ./cc-test-reporter after-build -t lcov

# TODO: Notifications on failure ?

# TODO: add coveralls
# TODO: Add npm publishing on tags
